### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by Romaric20** [GarrettLab/HabitatConnectivity#115]
Hi @krishnakeshav , @AaronPlex 
I ran a habitat connectivity analysis for Lauraceae using all 4 parameters (individually and together) using the function "msean" and got the same result always.
Plex and I also ran the sensitive analysis with just betweenness, and the result is different.

It seems like the "msean" function need to be validated.

**Comment by krishnakeshav** [comment]
The results seems consistent in the latest run using github version. Rmd shared over email.
**Closeness** -
![00004c](https://github.com/GarrettLab/HabitatConnectivity/assets/10234166/31071684-d3d3-4d69-891f-e693ef37fc3c)

**Betweeness**
![000046](https://github.com/GarrettLab/HabitatConnectivity/assets/10234166/15d6bdf8-4cb9-4d90-b539-bdb3c8504a17)

@AaronPlex @Romaric20 @GarrettLab 

Thus, closing this now. Feel free open this again if you notice inconsistent results.
